name: Christian Socialism
favicon: null
layout_spectrum: 0.75206
typography_spectrum: 0.9964440998155624
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#121411'
    - '#f2c866'
    - '#9e8b47'
    - '#364c26'
    - '#ef7029'
  brandStrength: 0.875
  lightness: 0.8346437376458198
  saturation: 0.653893411392346
  rhythmicContrast: 0.6712697758339345
purpose: []
