name: Christian Socialism
favicon: null
layout_spectrum: 0.75206
typography_spectrum: 0.9964440998155624
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c5302a'
    - '#ffffff'
    - '#000000'
    - '#d78883'
    - '#4c3c49'
  brandStrength: 0.8125
  lightness: 0.8346437376458198
  saturation: 0.653893411392346
  rhythmicContrast: 0.6712697758339345
purpose: []
